### ISSUE TITLE
cffi error in 0.1.3

### ISSUE THREAD

**Issue by ianxm** [TheHippo/hxfcgi#10]
I get the same result on linux 32 and 64 bit.  I get one error with the precompiled binaries from your haxelib package and a different one if I compile from the repo locally.  I'm calling the fcgi from nginx, with supervisord spawning the fcgi process.  I'm using haxe 2.10, hxcpp 2.10.3, and neko 1.8.2 (I tried switching to neko 2 but nothing worked so I reverted).

using the hxfcgi.ndll from the 0.1.2 haxelib package works.

when I use the hxfcgi.ndll from the 0.1.3 haxelib package it crashes when initializing the fcgi listener.  this is the error message:

```
Uncaught exception - load.c(237) : Failed to load library : /home/.../hxfcgi.ndll (/home/.../hxfcgi.ndll: undefined symbol: FCGX_IsCGI)
```

when I run using the hxfcgi.ndll (0.1.2 or 0.1.3) compiled locally it crashes when handling the request. this is the error message:

```
Could not link plugin to process (hxCFFILoader.h 656)
```

when it crashes, the function trying to resolve (`inName`) is `alloc_abstract`.  it's called from hxfcgi_create_request() around hxfcgi.cpp:53. it's defined in CFFI.cpp.  the same error occurs if the fcgi file is run directly (neko test.n) instead of calling it through a webserver.

I tried copying all of the ndlls and the libneko.so into the working dir but it didn't help.  the only file that seems to matter is hxfcgi.ndll.  if 0.1.2 from the haxelib package is in the working dir then it works, if 0.1.3 is there is fails.  I compiled the 0.1.2 source in the haxelib dir and also cloned and compiled the latest and then reset to the 0.1.2 tag but the hxfcgi.ndll's that were built weren't the same as the one from the package and produced the same error above.

I also tried hxcpp 3.0.0 but that didn't make a difference so I reverted.

**Comment by TheHippo** [comment]
The 0.1.3 version is still kind of unstable. There are some issues with the nekoapi.ndll and compatibility with neko2.

Are you sure you have the nekoapi.ndll available which matches your platform?

**Comment by ianxm** [comment]
I'm fine with using 0.1.2 for the time being, and I'd be happy to help you update and test 0.1.3 at some point.

I should be able to compile a usable 0.1.2, though.  I tried the nekoapi.ndll that worked with the precompiled hxfcgi.ndll and I tried the one in the hxcpp/.../Linux/ directory.  I also recompiled hxcpp and tried the nekoapi.ndll that was built.

did you patch hxcpp when you compiled the hxfcgi.ndll that you packaged or was it a haxelib version?  do you know which version?  I tried 2.10.3 and 3.0.0.

**Comment by TheHippo** [comment]
I am using hxcpp as it comes when installing though haxelib, so binaries for the current 0.1.3 were created with hxcpp 3.0.0.

As for now I want wait a little bit until all the Haxe 3 and neko 2 issues get resolved and then clean hxfcgi up.

**Comment by ianxm** [comment]
ok.  I'm in no rush to move to haxe 3 and neko 2.  also I can wait for the next release of hxfcgi if 0.1.3 it is unstable.  I will test the precompiled 0.1.2 hxfcgi.ndll on linux 64 bit tonight.  if that works for me I'll just wait for the next stable release.  if it doesn't work I'll go back to trying to compile it.

I suspect that the 0.1.2 binaries I'm creating aren't working because I'm compiling against a different version of hxcpp than the one you used.  if that's the case, the hxfcgi makefile should be updated to point to the specific hxcpp version you're using.

**Comment by TheHippo** [comment]
The binaries shipped on haxelib are compiled against the Ubuntu package of `libfcgi-dev`. Maybe there are some incompatibilities with other server / distros.

**Comment by ianxm** [comment]
good thought, but I'm also using `libfcgi-dev` on ubuntu.  I'm going to test the 64 bit version on rhel6, and I'm compiling libfcgi from source there, so that may cause problems.

**Comment by ianxm** [comment]
I tested the linux 64 bit precompiled ndlls for 0.1.2 and they worked so I'll stick with 0.1.2 until the next release.

thanks.
