### ISSUE TITLE
Problem compiling on OSX Mavericks

### ISSUE THREAD

**Issue by JWambaugh** [TheHippo/hxfcgi#12]
I have the fcgi homebrew installed. After adding my include path to the make file, I get this error:
    make HXCPP_M64=1
    rm -f bin/hxfcgi.ndll
    rm -f src/hxfcgi.o src/request.o src/basic.o src/data.o
    g++ -O2 -s -Wall -shared -I/usr/lib/haxe/lib/hxcpp/3,0,2/include/ -I/usr/local/include/ -D hxcpp -D HXCPP_M64 -fPIC -c -o src/hxfcgi.o src/hxfcgi.cpp
    clang: warning: argument unused during compilation: '-s'
    clang: warning: argument unused during compilation: '-shared'
    g++ -O2 -s -Wall -shared -I/usr/lib/haxe/lib/hxcpp/3,0,2/include/ -I/usr/local/include/ -D hxcpp -D HXCPP_M64 -fPIC -c -o src/request.o src/request.cpp
    clang: warning: argument unused during compilation: '-s'
    clang: warning: argument unused during compilation: '-shared'
    In file included from src/request.cpp:24:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/sstream:174:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/ostream:131:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/ios:216:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/__locale:15:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/string:437:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/cstdio:170:9: error: no member named 'FCGI_fgetpos' in
          the global namespace; did you mean 'FCGI_fgets'?
    using ::fgetpos;
          ~~^
    /usr/local/include/fcgi_stdio.h:174:18: note: expanded from macro 'fgetpos'
    #define fgetpos  FCGI_fgetpos
                     ^
    /usr/local/include/fcgi_stdio.h:91:19: note: 'FCGI_fgets' declared here
    DLLAPI char      *FCGI_fgets(char *str, int size, FCGI_FILE *fp);
                      ^
    In file included from src/request.cpp:24:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/sstream:174:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/ostream:131:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/ios:216:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/__locale:15:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/string:437:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/cstdio:172:9: error: no member named 'FCGI_fsetpos' in
          the global namespace; did you mean 'FCGI_fgets'?
    using ::fsetpos;
          ~~^
    /usr/local/include/fcgi_stdio.h:176:18: note: expanded from macro 'fsetpos'
    #define fsetpos  FCGI_fsetpos
                     ^
    /usr/local/include/fcgi_stdio.h:91:19: note: 'FCGI_fgets' declared here
    DLLAPI char      *FCGI_fgets(char *str, int size, FCGI_FILE *fp);
                      ^
    src/request.cpp:34:7: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
                    if (!FCGI_Accept()==0) {
                        ^             ~~
    src/request.cpp:34:7: note: add parentheses after the '!' to evaluate the comparison first
                    if (!FCGI_Accept()==0) {
                        ^
                         (               )
    src/request.cpp:34:7: note: add parentheses around left hand side expression to silence this warning
                    if (!FCGI_Accept()==0) {
                        ^
                        (             )
    1 warning and 2 errors generated.

**Comment by TheHippo** [comment]
I don't own a Mac so it is really hard for me to tell what's going wrong.

The only thing I know that you are the first one I know who is apparently using the XCode toolchain instead the original version of gcc.

**Comment by JWambaugh** [comment]
Ok. I'll give it a try with gcc. Thanks!

**Comment by TheHippo** [comment]
I'm sorry that I couldn't be more helpful. But this project just started as a prof-of-concept experiment and I stoped working on it 3 years ago and do not use anywhere.

**Comment by JWambaugh** [comment]
Ok, I was afraid of that :)
