### ISSUE TITLE
While loading 'fcgi.ndll': Could not load module fcgi@hxfcgi_create_request__0

### ISSUE THREAD

**Issue by ovidiugabriel** [TheHippo/hxfcgi#13]
Hello,

I have troubles while loading **fcgi.ndll** into my Haxe program. I am targeting HXCPP on Windows 10. The error message is: **Could not load module fcgi@hxfcgi_create_request__0**

Maybe this backtrace helps.

```
Web.hx:330: load(hxfcgi_create_request, 0)
Lib.hx:30: load(fcgi, hxfcgi_create_request, 0)
Web.hx:337: Could not load module fcgi@hxfcgi_create_request__0
```

I have my **fcgi.ndll** in the following path: **c:\HaxeToolkit\neko\fcgi.ndll**

I've checked with Dependency Walker and the symbol hxfcgi_create_request__0 is indeed present in the DLL file. I also rebuilt fcgi.dll and tried to use HXCPP_M64 but the result is not different.

I also reported this problem to Haxe Foundation: https://github.com/HaxeFoundation/neko/issues/145

**Comment by TheHippo** [comment]
If this isn't a Haxe CPP problem then maybe something has changed how to bind to dynamic libraries. (Keep in mind, the last real contribution to this repository was made in 2013.)

It is a little bit difficult for me to help, since I haven't touched a Windows in years and not actively using Haxe anymore. 

If you find a way to fix this I would happily accept a pull request.

**Comment by ovidiugabriel** [comment]
Of course, I will submit a fix as soon as I find out the right way to load it. 

Sorry to hear that you are not using Haxe anymore. In 2013 I didn't even knew that such a tool is already implemented and ready to use on the market.

**Comment by ovidiugabriel** [comment]
I just grabbed a part of your code and typed cpp.Web class as extern. Maybe if I have time in my next vacation I can make a fork and compile the entire library as haxe compile time extern instead of nekovm runtime loaded library.

Haxe externs are great. Btw, I think I used an older version of your lib from bit bucket. I don't know which is newer.

**Comment by TheHippo** [comment]
Do you mean this one: https://bitbucket.org/yar3333/haxe-fcgi

It seems to be updated from time to time.

**Comment by ovidiugabriel** [comment]
> Do you mean this one: https://bitbucket.org/yar3333/haxe-fcgi
> 
> It seems to be updated from time to time.

That's not yours?

**Comment by TheHippo** [comment]
> That's not yours?

No. I usually always have the same username everywhere. Also this library has a different name. `haxe-fcgi` vs. `hxfcgi`.
