### ISSUE TITLE
problem with cache

### ISSUE THREAD

**Issue by go2ghana** [TheHippo/hxfcgi#7]
When I use the Web.cacheModule function with an swf movieclip as content
the output gets corrupted with mod_fcgi after the first run.
See my example at http://go2ghana.net/haxe/cpp/SWFD.fcgi
This is a cpp target but the behavior is the same with the neko target.
The output remains correct if I don't use the cache function...

**Comment by vixns** [comment]
The output is not corrupted, it's just about content type.
I can't reproduce (but not using apache), aren't you setting the content-type before caching ?

**Comment by go2ghana** [comment]
Am 14.05.2011 10:16, schrieb vixns:

> The output is not corrupted, it's just about content type.
> I can't reproduce (but not using apache), aren't you setting the content-type before caching ?
> 
> Yeah - embarrassing - moving the setHeader to the run function solved my 
> problem.
> Now the comparison is quite complete: http://go2ghana.net/devel/compare.php

I am wondering where there is still room to improve.

Thx,
Axel

**Comment by vixns** [comment]
Many thanks for finishing this bench, it's helps a lot.
We're waiting for your announcement in the haxe list.

Raw performance should be near optimal, we may have some compilation flags to tweak, and use more const, etc...
The next big thing will be to bench and improve high concurrency.

**Comment by TheHippo** [comment]
thank for the benchmarks...

**Comment by go2ghana** [comment]
Am 14.05.2011 15:26, schrieb vixns:

> Many thanks for finishing this bench, it's helps a lot.
> We're waiting for your announcement in the haxe list.
> 
> I was feeling that I missed something and added a native fcgi c version 
> of the program
> to the bench http://go2ghana.net/devel/compare.php and it is a lot 
> faster then the hxfcgi version :(
> Maybe we could find why and tweak it further b4 publishing?
> Raw performance should be near optimal, we may have some compilation flags to tweak, and use more const, etc...
> The next big thing will be to bench and improve high concurrency.
