### ISSUE TITLE
Tested against Haxe 3.0?

### ISSUE THREAD

**Issue by tbrannam** [TheHippo/hxfcgi#9]
I'm trying to get Haxe/Neko to run as part of a fastcgi script in a shared dreamhost environment - I think that I've picked up everything I need, and I successfully got everything to compile.  I can get a perl fastcgi to respond to fastcgi calls - but my neko code times out.

FastCGI: comm with (dynamic) server "/home/example/example.com/Site.fcgi" aborted: (first read) idle timeout (60 sec)

Where Site.fcgi is a script that sets up all the environment vars for haxe.

Have you tested on Haxe 3.0?

**Comment by TheHippo** [comment]
For the Haxe 3.0 question: f29b214c93a5b83cfdfaa1fe489724dc8e5eb1b1 and the [official library page](http://lib.haxe.org/p/hxfcgi) :wink: 

Apart from that, about your questions which do not relate to the topic of this issue:
- Which server is used?
- Does CGI work?
- How long / how many requests until the error occurs?
- Where did you get the error message?
- How many processes where spawned?
- Which neko version?

**Comment by tbrannam** [comment]
Thanks for the clarification on the 3.0 support.  
As for additional details:  
- Apache server, 
- CGI doesn't work either, which makes me suspect runtime environment more, 
- fails on first call
- one process spawned (and aborted)
  -neko 2.0.0 (built from source tarball).

New runtime detail, if I run directly the the output of 
$haxe -main Example -lib hxfcgi -D HXFCGI -neko example.n

$neko example.n
{ h => #abstract }

which appears to be the output from the output of this source line
Lib.println(Web.getParams());

I'll continue digging deeper - I'm suspecting this is more a runtime/environment issue, but if the #abstract message sounds familiar - I'd accept suggestions on how to address it as well.

**Comment by TheHippo** [comment]
The `#abstract` just indicates there is a value which is not created by neko (means, comes from a ndll). As long as there are no "Wrong ELF class" or "Could not find symbol XXX" errors the objects from the ndll are loaded correctly.

I currently do not have any 32bit Linux running (I just assumed you are on Linux 32bit??), so the binary shipped via haxelib is cross-compiled against fcgi-dev from Ubuntu 12.04. Maybe Dreamhost uses a different incompatible version? Have you tried to compiled the ndlls by yourself?

**Comment by tbrannam** [comment]
uname -m reports: x86_64 - i've pulled a 'git' version of this project into haxelib and did compile that as well.  Perhaps from the command-line the Web object can't vend getParams (since there isn't a server?)

**Comment by TheHippo** [comment]
The parameters are usually transmitted via environment variables, but you are right you can't get them when running the whole thing from the command line.

I do not have any access to any dreamhost hosting, so it is kind of hard for me reproduce your error. (Also I moved away from Apache a while ago.)

Please not that there are currently some [issues](https://groups.google.com/d/msg/haxelang/nRTOmujstjk/C03ux4XMoeEJ) with nekoapi.ndll for 64bit and neko 2.0.

P.S.: Sorry that this must be kind of frustrating for you, but this library isn't production ready yet and I do not have the resources to test and compile for various possible configurations.

**Comment by tbrannam** [comment]
Fair enough - I will continue trying to debug it -- I'll write up a solution if one becomes clear.

**Comment by TheHippo** [comment]
Let me know if figure something out. :smiley:

**Comment by yar3333** [comment]
New installation, Ubuntu 12, 64bit, haxe3, neko2: with a hxfcgi.ndll version from haxelib I get the strange error. If I try to recompile ndll from sources I see error after run (like "symbol ... not found"). Also check: makefile had a "-m32" hardcoded! Now I downgrade to haxe2.10, neko1.8.2 and hxfcgi0.1.2 and all working good.
